import io
import logging
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger(__name__)

_font_registered = False


def _register_fonts():
    global _font_registered
    if _font_registered:
        return
    try:
        pdfmetrics.registerFont(TTFont("WenQuanYi", "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc", subfontIndex=0))
    except Exception:
        try:
            pdfmetrics.registerFont(TTFont("WenQuanYi", "C:/Windows/Fonts/msyh.ttc", subfontIndex=0))
        except Exception:
            logger.warning("No CJK font found, PDF Chinese text may not render")
    _font_registered = True


def generate_bilingual_pdf(lecture_data: dict) -> bytes:
    _register_fonts()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    style_title_de = ParagraphStyle(
        "TitleDE", fontName="Helvetica-Bold", fontSize=14, leading=18,
        spaceAfter=4, textColor="#1e3a5f",
    )
    style_title_zh = ParagraphStyle(
        "TitleZH", fontName="WenQuanYi", fontSize=12, leading=16,
        spaceAfter=12, textColor="#666666",
    )
    style_de = ParagraphStyle(
        "DE", fontName="Helvetica", fontSize=9, leading=13,
        spaceAfter=2, textColor="#1e293b",
    )
    style_zh = ParagraphStyle(
        "ZH", fontName="WenQuanYi", fontSize=9, leading=13,
        spaceAfter=6, textColor="#64748b",
    )
    style_meta = ParagraphStyle(
        "Meta", fontName="Helvetica", fontSize=7, leading=10,
        spaceAfter=12, textColor="#94a3b8",
    )
    style_notice = ParagraphStyle(
        "Notice", fontName="Helvetica", fontSize=6, leading=8,
        alignment=1, textColor="#cbd5e1",
    )

    story = []

    title_de = lecture_data.get("title_de", "")
    title_zh = lecture_data.get("title_zh", "")
    location = lecture_data.get("location", "")
    lecture_date = lecture_data.get("lecture_date", "")

    if title_de:
        story.append(Paragraph(_escape(title_de), style_title_de))
    if title_zh:
        story.append(Paragraph(_escape(title_zh), style_title_zh))

    meta_parts = []
    if location:
        meta_parts.append(_escape(location))
    if lecture_date:
        meta_parts.append(_escape(str(lecture_date)))
    if meta_parts:
        story.append(Paragraph(" — ".join(meta_parts), style_meta))

    story.append(Spacer(1, 6))

    for para in lecture_data.get("paragraphs", []):
        for sent in para.get("sentences", []):
            text_de = sent.get("text_de", "")
            text_zh = sent.get("text_zh")

            if text_de:
                story.append(Paragraph(_escape(text_de), style_de))
            if text_zh:
                story.append(Paragraph(_escape(text_zh), style_zh))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Steiner Reader — 仅供个人学习使用", style_notice))

    doc.build(story)
    return buffer.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
